export const SOUNDMARKS = [
  {
    id: "kotaete-grand-prix",
    songId: "kotaete",
    progress: 0.10,
    x: 0.20,
    y: 0.18,
    symbol: "♪",
    title: "グランプリ「こたえて」",
    body: "「こたえて」は、初音ミク「マジカルミライ 2026」楽曲コンテストのグランプリ作品です。作者は imie さんです。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "kotaete-live-stage",
    songId: "kotaete",
    progress: 0.31,
    x: 0.55,
    y: 0.27,
    symbol: "♫",
    title: "ライブで演奏される歌",
    body: "グランプリ作品は、初音ミク「マジカルミライ 2026」のライブで演奏されます。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "kotaete-sonare-theme",
    songId: "kotaete",
    progress: 0.56,
    x: 0.28,
    y: 0.38,
    symbol: "♩",
    title: "湖のソナーレ",
    body: "ソナーレはイタリア語で「奏でる」という意味。浜松での初開催にあわせて、湖と音楽をモチーフにしたテーマです。",
    sourceLabel: "piapro blog",
    sourceUrl: "https://blog.piapro.net/2026/03/b2603051.html",
  },
  {
    id: "kotaete-imie-comment",
    songId: "kotaete",
    progress: 0.82,
    x: 0.66,
    y: 0.23,
    symbol: "♬",
    title: "imieさんの受賞コメント",
    body: "imie さんは結果発表で、ミクさんがこの曲をステージで歌って踊る姿を楽しみにしている、とコメントしています。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "curtain-hamamatsu-first",
    songId: "after-the-curtain",
    progress: 0.10,
    x: 0.24,
    y: 0.22,
    symbol: "♭",
    title: "初開催の浜松",
    body: "マジカルミライ 2026 は、TOKYO・OSAKAに加えて初めて HAMAMATSU でも開催されます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-act-city",
    songId: "after-the-curtain",
    progress: 0.32,
    x: 0.60,
    y: 0.33,
    symbol: "♯",
    title: "アクトシティ浜松",
    body: "HAMAMATSU会場はアクトシティ浜松。大ホール、展示イベントホール、コングレスセンターでライブと企画展が開かれます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-live-exhibition",
    songId: "after-the-curtain",
    progress: 0.57,
    x: 0.36,
    y: 0.43,
    symbol: "♮",
    title: "ライブと企画展",
    body: "マジカルミライは、初音ミクたちバーチャルシンガーの3DCGライブと、創作の楽しさを体感できる企画展を併催するイベントです。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-creative-place",
    songId: "after-the-curtain",
    progress: 0.82,
    x: 0.68,
    y: 0.18,
    symbol: "♪",
    title: "創作でつながる場所",
    body: "マジカルミライは、作品やクリエイター、同じキャラクターが好きな人たちが「創作」をきっかけにつながる場所を目指しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-lake-light",
    songId: "shutter-chance",
    progress: 0.10,
    x: 0.18,
    y: 0.27,
    symbol: "♫",
    title: "光を写す湖",
    body: "2026年のメインビジュアルは、湖や自然からの光に輝く様子と、音楽が華やかに響く様子を表現しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-main-visual-artist",
    songId: "shutter-chance",
    progress: 0.33,
    x: 0.51,
    y: 0.40,
    symbol: "♩",
    title: "緜さんのメインビジュアル",
    body: "初音ミク「マジカルミライ 2026」のメインビジュアルは、イラストレーターの 緜 さんが担当しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-costume-motifs",
    songId: "shutter-chance",
    progress: 0.58,
    x: 0.30,
    y: 0.20,
    symbol: "♬",
    title: "ひまわりと蝶と音符",
    body: "2026年の衣装デザインには、ひまわり、蝶、音符のモチーフがアクセントとして配されています。",
    sourceLabel: "piapro blog",
    sourceUrl: "https://blog.piapro.net/2026/03/b2603051.html",
  },
  {
    id: "shutter-theme-song",
    songId: "shutter-chance",
    progress: 0.82,
    x: 0.64,
    y: 0.35,
    symbol: "♭",
    title: "テーマソング「空に免じて」",
    body: "マジカルミライ 2026 のテーマソングは、傘村トータ feat. 初音ミク「空に免じて」。編曲は島田昌典が担当しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "last-band-six-singers",
    songId: "last-band",
    progress: 0.10,
    x: 0.22,
    y: 0.36,
    symbol: "♯",
    title: "六人のバーチャルシンガー",
    body: "マジカルミライ 2026 では、初音ミク、鏡音リン、鏡音レン、巡音ルカ、MEIKO、KAITO がイベントを盛り上げます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "last-band-city-of-music",
    songId: "last-band",
    progress: 0.32,
    x: 0.58,
    y: 0.23,
    symbol: "♮",
    title: "音楽のまち浜松",
    body: "浜松市は、ピアノをはじめとする楽器産業を背景に発展し、昭和56年から「音楽のまちづくり」を掲げてきました。",
    sourceLabel: "浜松市",
    sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/bunka/intro/mc/index.html",
  },
  {
    id: "last-band-instrument-museum",
    songId: "last-band",
    progress: 0.57,
    x: 0.34,
    y: 0.18,
    symbol: "♪",
    title: "楽器博物館",
    body: "浜松市楽器博物館は、日本初の公立楽器博物館です。世界各地から集めた約1500点の資料を地域、種類、年代別に展示しています。",
    sourceLabel: "Hamamatsu Museum",
    sourceUrl: "https://www.gakkihaku.jp/en/",
  },
  {
    id: "last-band-music-capital",
    songId: "last-band",
    progress: 0.82,
    x: 0.66,
    y: 0.42,
    symbol: "♫",
    title: "楽器のまちから音楽の都へ",
    body: "浜松市は、楽器のまちから文化面での発展を目指し、国際レベルから市民レベルまで多くの音楽施策を続けてきました。",
    sourceLabel: "浜松市",
    sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/bunka/intro/mc/index.html",
  },
  {
    id: "toritsukurogy-bentenjima-torii",
    songId: "toritsukurogy",
    progress: 0.10,
    x: 0.24,
    y: 0.20,
    symbol: "♩",
    title: "弁天島の鳥居",
    body: "弁天島海浜公園では、浜名湖に立つ赤い鳥居がシンボルタワーとして親しまれています。",
    sourceLabel: "浜松・浜名湖だいすきネット",
    sourceUrl: "https://hamamatsu-daisuki.net/course/190/",
  },
  {
    id: "toritsukurogy-lake-hamana",
    songId: "toritsukurogy",
    progress: 0.32,
    x: 0.56,
    y: 0.38,
    symbol: "♬",
    title: "浜名湖のほとり",
    body: "浜松市の公式観光サイトでは、浜松を大都市の喧騒から離れて落ち着ける、静かな湖畔のある街として紹介しています。",
    sourceLabel: "Visit Hamamatsu",
    sourceUrl: "https://www.hamamatsu-japan.com/en/",
  },
  {
    id: "toritsukurogy-red-on-water",
    songId: "toritsukurogy",
    progress: 0.57,
    x: 0.33,
    y: 0.31,
    symbol: "♭",
    title: "湖に立つ赤",
    body: "浜名湖に立つ赤い鳥居は、弁天島の風景を象徴する存在です。湖面、夕景、ライトアップとともに記憶される景色です。",
    sourceLabel: "浜松・浜名湖だいすきネット",
    sourceUrl: "https://hamamatsu-daisuki.net/course/190/",
  },
  {
    id: "toritsukurogy-lake-creatures",
    songId: "toritsukurogy",
    progress: 0.82,
    x: 0.68,
    y: 0.26,
    symbol: "♯",
    title: "浜名湖の生きもの",
    body: "浜松市の観光サイトでは、浜名湖の生き物を紹介する学習施設「浜名湖体験学習施設ウォット」が紹介されています。",
    sourceLabel: "Visit Hamamatsu",
    sourceUrl: "https://www.hamamatsu-japan.com/en/",
  },
  {
    id: "takeover-three-venues",
    songId: "takeover",
    progress: 0.10,
    x: 0.20,
    y: 0.30,
    symbol: "♮",
    title: "三会場へ広がる響き",
    body: "マジカルミライ 2026 は、HAMAMATSU、OSAKA、TOKYO の3会場で開催されます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-hatsune-miku",
    songId: "takeover",
    progress: 0.32,
    x: 0.54,
    y: 0.21,
    symbol: "♪",
    title: "初音ミクとは？",
    body: "初音ミクは、歌詞とメロディーを入力すると歌わせることができる歌声合成ソフトウェアとして、2007年に企画・開発されました。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-creative-culture",
    songId: "takeover",
    progress: 0.57,
    x: 0.36,
    y: 0.41,
    symbol: "♫",
    title: "58万人の創作文化",
    body: "マジカルミライは2013年から開催され、国内では累計58万人以上を動員しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-miku-expo",
    songId: "takeover",
    progress: 0.82,
    x: 0.66,
    y: 0.35,
    symbol: "♬",
    title: "MIKU EXPOの広がり",
    body: "初音ミクの世界ツアーシリーズ「MIKU EXPO」は、これまでに50都市で120公演を巡演しています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
];

export const SOUNDMARK_TRANSLATIONS = {
  ko: {
    "kotaete-grand-prix": {
      title: "그랑프리 「こたえて」",
      body: "「こたえて」는 하츠네 미쿠 「매지컬 미라이 2026」 악곡 콘테스트의 그랑프리 작품입니다. 작가는 imie 님입니다.",
    },
    "kotaete-live-stage": {
      title: "라이브에서 연주되는 노래",
      body: "그랑프리 작품은 하츠네 미쿠 「매지컬 미라이 2026」 라이브에서 연주됩니다.",
    },
    "kotaete-sonare-theme": {
      title: "湖のソナーレ",
      body: "Sonare는 이탈리아어로 「연주하다」라는 뜻입니다. 하마마쓰 첫 개최에 맞춰 호수와 음악을 모티프로 삼은 테마입니다.",
      sourceLabel: "piapro blog",
    },
    "kotaete-imie-comment": {
      title: "imie 님의 수상 코멘트",
      body: "imie 님은 결과 발표에서 미쿠가 이 곡을 스테이지에서 부르고 춤추는 모습을 기대하고 있다고 코멘트했습니다.",
    },
    "curtain-hamamatsu-first": {
      title: "첫 개최지 하마마쓰",
      body: "매지컬 미라이 2026은 TOKYO, OSAKA에 더해 처음으로 HAMAMATSU에서도 개최됩니다.",
    },
    "curtain-act-city": {
      title: "액트시티 하마마쓰",
      body: "HAMAMATSU 회장은 액트시티 하마마쓰입니다. 대홀, 전시 이벤트홀, 콩그레스 센터에서 라이브와 기획전이 열립니다.",
    },
    "curtain-live-exhibition": {
      title: "라이브와 기획전",
      body: "매지컬 미라이는 하츠네 미쿠 등 버추얼 싱어의 3DCG 라이브와 창작의 즐거움을 체감할 수 있는 기획전이 함께 열리는 이벤트입니다.",
    },
    "curtain-creative-place": {
      title: "창작으로 이어지는 장소",
      body: "매지컬 미라이는 작품과 크리에이터, 같은 캐릭터를 좋아하는 사람들이 「창작」을 계기로 이어지는 장소를 목표로 합니다.",
    },
    "shutter-lake-light": {
      title: "빛을 비추는 호수",
      body: "2026년 메인 비주얼은 호수와 자연에서 오는 빛으로 반짝이는 모습, 그리고 음악이 화려하게 울려 퍼지는 모습을 표현합니다.",
    },
    "shutter-main-visual-artist": {
      title: "緜 님의 메인 비주얼",
      body: "하츠네 미쿠 「매지컬 미라이 2026」의 메인 비주얼은 일러스트레이터 緜 님이 담당했습니다.",
    },
    "shutter-costume-motifs": {
      title: "해바라기와 나비와 음표",
      body: "2026년 의상 디자인에는 해바라기, 나비, 음표 모티프가 포인트로 배치되어 있습니다.",
      sourceLabel: "piapro blog",
    },
    "shutter-theme-song": {
      title: "테마송 「空に免じて」",
      body: "매지컬 미라이 2026의 테마송은 카사무라 토타 feat. 하츠네 미쿠 「空に免じて」입니다. 편곡은 시마다 마사노리가 담당했습니다.",
    },
    "last-band-six-singers": {
      title: "여섯 명의 버추얼 싱어",
      body: "매지컬 미라이 2026에서는 하츠네 미쿠, 카가미네 린, 카가미네 렌, 메구리네 루카, MEIKO, KAITO가 이벤트를 북돋웁니다.",
    },
    "last-band-city-of-music": {
      title: "음악의 도시 하마마쓰",
      body: "하마마쓰시는 피아노를 비롯한 악기 산업을 배경으로 발전했으며, 쇼와 56년부터 「음악의 도시 만들기」를 내걸어 왔습니다.",
      sourceLabel: "하마마쓰시",
    },
    "last-band-instrument-museum": {
      title: "악기박물관",
      body: "하마마쓰시 악기박물관은 일본 최초의 공립 악기박물관입니다. 세계 각지에서 모은 약 1500점의 자료를 지역, 종류, 시대별로 전시하고 있습니다.",
      sourceLabel: "Hamamatsu Museum",
    },
    "last-band-music-capital": {
      title: "악기의 도시에서 음악의 도시로",
      body: "하마마쓰시는 악기의 도시에서 문화적인 발전을 목표로, 국제 수준부터 시민 수준까지 다양한 음악 정책을 이어 왔습니다.",
      sourceLabel: "하마마쓰시",
    },
    "toritsukurogy-bentenjima-torii": {
      title: "벤텐지마의 토리이",
      body: "벤텐지마 해변공원에서는 하마나코에 서 있는 붉은 토리이가 상징탑으로 사랑받고 있습니다.",
      sourceLabel: "하마마쓰·하마나코 다이스키넷",
    },
    "toritsukurogy-lake-hamana": {
      title: "하마나코 호숫가",
      body: "하마마쓰시 공식 관광 사이트는 하마마쓰를 대도시의 소음에서 벗어나 차분히 머물 수 있는 조용한 호숫가가 있는 도시로 소개합니다.",
      sourceLabel: "Visit Hamamatsu",
    },
    "toritsukurogy-red-on-water": {
      title: "호수에 선 붉은색",
      body: "하마나코에 서 있는 붉은 토리이는 벤텐지마 풍경을 상징하는 존재입니다. 수면, 석양, 라이트업과 함께 기억되는 풍경입니다.",
      sourceLabel: "하마마쓰·하마나코 다이스키넷",
    },
    "toritsukurogy-lake-creatures": {
      title: "하마나코의 생물",
      body: "하마마쓰시 관광 사이트에는 하마나코의 생물을 소개하는 학습 시설 「하마나코 체험학습시설 Wotto」가 소개되어 있습니다.",
      sourceLabel: "Visit Hamamatsu",
    },
    "takeover-three-venues": {
      title: "세 회장으로 퍼지는 울림",
      body: "매지컬 미라이 2026은 HAMAMATSU, OSAKA, TOKYO 세 회장에서 개최됩니다.",
    },
    "takeover-hatsune-miku": {
      title: "하츠네 미쿠란?",
      body: "하츠네 미쿠는 가사와 멜로디를 입력하면 노래하게 할 수 있는 노래 음성 합성 소프트웨어로, 2007년에 기획·개발되었습니다.",
    },
    "takeover-creative-culture": {
      title: "58만 명의 창작 문화",
      body: "매지컬 미라이는 2013년부터 개최되어, 일본 국내에서 누적 58만 명 이상을 동원했습니다.",
    },
    "takeover-miku-expo": {
      title: "MIKU EXPO의 확장",
      body: "하츠네 미쿠의 월드 투어 시리즈 「MIKU EXPO」는 지금까지 50개 도시에서 120회 공연을 순회했습니다.",
    },
  },
  en: {
    "kotaete-grand-prix": {
      title: "Grand Prix: “こたえて”",
      body: "“こたえて” is the Grand Prix winner of the Hatsune Miku “Magical Mirai 2026” Song Contest. It was created by imie.",
    },
    "kotaete-live-stage": {
      title: "A Song for the Live Stage",
      body: "The Grand Prix song will be performed at the Hatsune Miku “Magical Mirai 2026” live show.",
    },
    "kotaete-sonare-theme": {
      title: "湖のソナーレ",
      body: "Sonare means “to play” in Italian. For the first Hamamatsu event, the theme uses the lake and music as its motifs.",
      sourceLabel: "piapro blog",
    },
    "kotaete-imie-comment": {
      title: "imie’s Award Comment",
      body: "In the results announcement, imie commented that they look forward to seeing Miku sing and dance to this song on stage.",
    },
    "curtain-hamamatsu-first": {
      title: "Hamamatsu’s First Event",
      body: "Magical Mirai 2026 will be held in HAMAMATSU for the first time, alongside TOKYO and OSAKA.",
    },
    "curtain-act-city": {
      title: "Act City Hamamatsu",
      body: "The HAMAMATSU venue is Act City Hamamatsu. The live show and exhibition will be held in the Main Hall, Exhibition Event Hall, and Congress Center.",
    },
    "curtain-live-exhibition": {
      title: "Live Show and Exhibition",
      body: "Magical Mirai combines 3DCG live shows by Hatsune Miku and other virtual singers with an exhibition where visitors can experience the joy of creation.",
    },
    "curtain-creative-place": {
      title: "A Place Connected by Creation",
      body: "Magical Mirai aims to be a place where works, creators, and people who love the same characters connect through creation.",
    },
    "shutter-lake-light": {
      title: "A Lake That Captures Light",
      body: "The 2026 main visual expresses figures shining in light from the lake and nature, together with the brilliant resonance of music.",
    },
    "shutter-main-visual-artist": {
      title: "The Main Visual by 緜",
      body: "The main visual for Hatsune Miku “Magical Mirai 2026” was created by illustrator 緜.",
    },
    "shutter-costume-motifs": {
      title: "Sunflowers, Butterflies, and Notes",
      body: "The 2026 costume design uses sunflower, butterfly, and musical-note motifs as accents.",
      sourceLabel: "piapro blog",
    },
    "shutter-theme-song": {
      title: "Theme Song: “空に免じて”",
      body: "The Magical Mirai 2026 theme song is “空に免じて” by Kasamura Tota feat. Hatsune Miku. The arrangement is by Masanori Shimada.",
    },
    "last-band-six-singers": {
      title: "Six Virtual Singers",
      body: "At Magical Mirai 2026, Hatsune Miku, Kagamine Rin, Kagamine Len, Megurine Luka, MEIKO, and KAITO will bring energy to the event.",
    },
    "last-band-city-of-music": {
      title: "Hamamatsu, City of Music",
      body: "Hamamatsu developed around its musical-instrument industry, including pianos, and has promoted itself as a city of music since 1981.",
      sourceLabel: "Hamamatsu City",
    },
    "last-band-instrument-museum": {
      title: "The Museum of Musical Instruments",
      body: "The Hamamatsu Museum of Musical Instruments is Japan’s first public museum of musical instruments. It displays about 1,500 items collected from around the world by region, type, and period.",
      sourceLabel: "Hamamatsu Museum",
    },
    "last-band-music-capital": {
      title: "From Instrument City to Music Capital",
      body: "Hamamatsu has continued many music policies, from international-level efforts to citizen-level programs, aiming to grow culturally from a city of instruments into a city of music.",
      sourceLabel: "Hamamatsu City",
    },
    "toritsukurogy-bentenjima-torii": {
      title: "The Torii of Bentenjima",
      body: "At Bentenjima Seaside Park, the red torii standing in Lake Hamana is loved as a symbolic tower.",
      sourceLabel: "Hamamatsu/Hamanako Daisuki Net",
    },
    "toritsukurogy-lake-hamana": {
      title: "By Lake Hamana",
      body: "Hamamatsu’s official tourism site introduces the city as a place with a quiet lakeside where visitors can relax away from the bustle of big cities.",
      sourceLabel: "Visit Hamamatsu",
    },
    "toritsukurogy-red-on-water": {
      title: "Red Standing on the Lake",
      body: "The red torii standing in Lake Hamana is a symbol of the Bentenjima landscape, remembered together with the water, sunset views, and illumination.",
      sourceLabel: "Hamamatsu/Hamanako Daisuki Net",
    },
    "toritsukurogy-lake-creatures": {
      title: "Creatures of Lake Hamana",
      body: "Hamamatsu’s tourism site introduces Wotto, the Lake Hamana Experience Learning Facility, where visitors can learn about the lake’s living creatures.",
      sourceLabel: "Visit Hamamatsu",
    },
    "takeover-three-venues": {
      title: "Sound Spreading to Three Venues",
      body: "Magical Mirai 2026 will be held at three venues: HAMAMATSU, OSAKA, and TOKYO.",
    },
    "takeover-hatsune-miku": {
      title: "What Is Hatsune Miku?",
      body: "Hatsune Miku was planned and developed in 2007 as singing voice synthesis software that can sing when lyrics and melodies are entered.",
    },
    "takeover-creative-culture": {
      title: "A Creative Culture of 580,000 People",
      body: "Magical Mirai has been held since 2013 and has welcomed more than 580,000 visitors in Japan in total.",
    },
    "takeover-miku-expo": {
      title: "The Reach of MIKU EXPO",
      body: "Hatsune Miku’s world tour series “MIKU EXPO” has toured 50 cities with 120 performances to date.",
    },
  },
  "zh-Hans": {
    "kotaete-grand-prix": {
      title: "大奖作品「こたえて」",
      body: "「こたえて」是初音未来「Magical Mirai 2026」歌曲征集比赛的大奖作品。作者是 imie。",
    },
    "kotaete-live-stage": {
      title: "将在 Live 中演奏的歌曲",
      body: "大奖作品将在初音未来「Magical Mirai 2026」的 Live 中演奏。",
    },
    "kotaete-sonare-theme": {
      title: "湖のソナーレ",
      body: "Sonare 在意大利语中意为「演奏」。配合首次在滨松举办，本届主题以湖与音乐为设计动机。",
      sourceLabel: "piapro blog",
    },
    "kotaete-imie-comment": {
      title: "imie 的获奖感言",
      body: "imie 在结果发表中表示，很期待看到 Miku 在舞台上唱着这首歌并跳舞的样子。",
    },
    "curtain-hamamatsu-first": {
      title: "首次举办地滨松",
      body: "Magical Mirai 2026 除 TOKYO、OSAKA 外，也将首次在 HAMAMATSU 举办。",
    },
    "curtain-act-city": {
      title: "Act City 滨松",
      body: "HAMAMATSU 会场为 Act City 滨松。Live 与企划展将在大音乐厅、展示活动大厅和会议中心举办。",
    },
    "curtain-live-exhibition": {
      title: "Live 与企划展",
      body: "Magical Mirai 是同时举办初音未来等虚拟歌手 3DCG Live，以及能体验创作乐趣的企划展的活动。",
    },
    "curtain-creative-place": {
      title: "因创作而相连的地方",
      body: "Magical Mirai 以成为作品、创作者以及喜爱同一角色的人们通过「创作」相连的地方为目标。",
    },
    "shutter-lake-light": {
      title: "映照光芒的湖",
      body: "2026 年主视觉表现了在湖与自然之光中闪耀的样子，以及音乐华丽回响的样子。",
    },
    "shutter-main-visual-artist": {
      title: "緜 绘制的主视觉",
      body: "初音未来「Magical Mirai 2026」的主视觉由插画师 緜 负责。",
    },
    "shutter-costume-motifs": {
      title: "向日葵、蝴蝶与音符",
      body: "2026 年服装设计中，将向日葵、蝴蝶和音符作为点缀元素。",
      sourceLabel: "piapro blog",
    },
    "shutter-theme-song": {
      title: "主题曲「空に免じて」",
      body: "Magical Mirai 2026 的主题曲是傘村トータ feat. 初音ミク「空に免じて」。编曲由島田昌典负责。",
    },
    "last-band-six-singers": {
      title: "六位虚拟歌手",
      body: "在 Magical Mirai 2026 中，初音未来、镜音铃、镜音连、巡音流歌、MEIKO、KAITO 将共同为活动增添热度。",
    },
    "last-band-city-of-music": {
      title: "音乐之城滨松",
      body: "滨松市以钢琴等乐器产业为背景发展起来，并从昭和 56 年起提出了「音乐城市建设」。",
      sourceLabel: "滨松市",
    },
    "last-band-instrument-museum": {
      title: "乐器博物馆",
      body: "滨松市乐器博物馆是日本首座公立乐器博物馆。馆内按地区、种类和年代展示了从世界各地收集的约 1500 件资料。",
      sourceLabel: "Hamamatsu Museum",
    },
    "last-band-music-capital": {
      title: "从乐器之城到音乐之都",
      body: "滨松市从乐器之城出发，持续推进从国际层面到市民层面的多种音乐政策，力求在文化层面继续发展。",
      sourceLabel: "滨松市",
    },
    "toritsukurogy-bentenjima-torii": {
      title: "弁天岛的鸟居",
      body: "在弁天岛海滨公园，矗立于浜名湖中的红色鸟居作为象征塔受到人们喜爱。",
      sourceLabel: "滨松・浜名湖 Daisuki Net",
    },
    "toritsukurogy-lake-hamana": {
      title: "浜名湖畔",
      body: "滨松市官方旅游网站将滨松介绍为一座远离大城市喧嚣、拥有宁静湖畔、令人放松的城市。",
      sourceLabel: "Visit Hamamatsu",
    },
    "toritsukurogy-red-on-water": {
      title: "立于湖中的红色",
      body: "矗立在浜名湖中的红色鸟居，是象征弁天岛风景的存在。它与湖面、夕景和灯光一同被人铭记。",
      sourceLabel: "滨松・浜名湖 Daisuki Net",
    },
    "toritsukurogy-lake-creatures": {
      title: "浜名湖的生物",
      body: "滨松市旅游网站介绍了学习设施「浜名湖体验学习设施 Wotto」，在那里可以了解浜名湖的生物。",
      sourceLabel: "Visit Hamamatsu",
    },
    "takeover-three-venues": {
      title: "扩展至三大会场的回响",
      body: "Magical Mirai 2026 将在 HAMAMATSU、OSAKA、TOKYO 三大会场举办。",
    },
    "takeover-hatsune-miku": {
      title: "初音未来是什么？",
      body: "初音未来是 2007 年企划并开发的歌声合成软件，输入歌词和旋律后即可让其歌唱。",
    },
    "takeover-creative-culture": {
      title: "58 万人的创作文化",
      body: "Magical Mirai 自 2013 年起举办，在日本国内累计动员人数已超过 58 万。",
    },
    "takeover-miku-expo": {
      title: "MIKU EXPO 的扩展",
      body: "初音未来的世界巡演系列「MIKU EXPO」至今已巡演 50 座城市，举办 120 场公演。",
    },
  },
};
