export const SOUNDMARKS = [
  {
    id: "sonare-theme",
    progress: 0.10,
    x: 0.21,
    y: 0.115,
    symbol: "♪",
    title: "湖のソナーレ",
    body: "ソナーレは「奏でる」という意味。雄大な湖に面した音楽の都・浜松での初開催から、湖と音楽を重ねたテーマが生まれました。",
    tags: ["湖", "奏でる", "テーマ"],
    caption: "最初の波紋は、この湖が音を持つ場所だと知らせます。",
    sourceLabel: "piapro blog",
    sourceUrl: "https://blog.piapro.net/2026/03/b2603051.html",
  },
  {
    id: "hamamatsu-first",
    progress: 0.22,
    x: 0.52,
    y: 0.235,
    symbol: "✦",
    title: "初開催の浜松",
    body: "マジカルミライ 2026 は、東京・大阪に加えて初めて浜松で開催されます。会場はアクトシティ浜松です。",
    tags: ["浜松", "初開催", "創作"],
    caption: "曲が進むほど、はじめての開催地へ近づいていきます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "bentenjima-torii",
    progress: 0.34,
    x: 0.37,
    y: 0.172,
    symbol: "♬",
    title: "弁天島の鳥居",
    body: "弁天島海浜公園では、浜名湖に立つ赤い鳥居がシンボルタワーとして親しまれています。夕景やライトアップも湖の記憶になります。",
    tags: ["弁天島", "鳥居", "浜名湖"],
    caption: "鳥居のそばで生まれた波は、歌詞の反響として戻ってきます。",
    sourceLabel: "浜松・浜名湖だいすきネット",
    sourceUrl: "https://hamamatsu-daisuki.net/course/190/",
  },
  {
    id: "city-of-music",
    progress: 0.48,
    x: 0.62,
    y: 0.305,
    symbol: "♩",
    title: "音楽のまち浜松",
    body: "浜松市は、ピアノをはじめとする楽器産業を背景に発展し、昭和56年から音楽のまちづくりを掲げてきました。",
    tags: ["音楽", "楽器", "浜松"],
    caption: "湖面に浮かぶ文字も、まちの楽器のように響きます。",
    sourceLabel: "浜松市",
    sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/bunka/intro/mc/index.html",
  },
  {
    id: "creative-place",
    progress: 0.62,
    x: 0.27,
    y: 0.355,
    symbol: "◇",
    title: "創作でつながる場所",
    body: "マジカルミライは、ライブと企画展を通して創作の楽しさを体感するイベントです。初音ミクたちをきっかけに、作品と人がつながります。",
    tags: ["創作", "初音ミク", "未来"],
    caption: "クリックした印は、あなたがこの湖で見つけた小さな創作の跡です。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "lake-reflection",
    progress: 0.76,
    x: 0.48,
    y: 0.104,
    symbol: "⌁",
    title: "湖面の反響",
    body: "水面に落ちた声は、波紋になり、反射になり、少し遅れて戻ってきます。このアプリでは歌詞そのものが湖を鳴らします。",
    tags: ["波紋", "反響", "歌詞"],
    caption: "いま見えている揺れは、次の言葉へ渡るための余韻です。",
    sourceLabel: "湖のソナーレ",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "six-songs",
    progress: 0.88,
    x: 0.57,
    y: 0.425,
    symbol: "♫",
    title: "六つの受賞曲",
    body: "プログラミング・コンテストの対象は、楽曲コンテストで受賞した 6 曲。曲ごとの言葉、ビート、声量が、それぞれ異なる湖面を描きます。",
    tags: ["6曲", "TextAlive", "リリック"],
    caption: "同じ湖でも、選ぶ曲によって響き方は変わります。",
    sourceLabel: "TextAlive",
    sourceUrl: "https://developer.textalive.jp/events/magicalmirai2026/",
  },
];
