export const SOUNDMARKS = [
  {
    id: "kotaete-grand-prix",
    songId: "kotaete",
    progress: 0.10,
    x: 0.20,
    y: 0.18,
    symbol: "♪",
    title: "グランプリ「こたえて」",
    body: "「こたえて」は、初音ミク「マジカルミライ 2026」楽曲コンテストのグランプリ作品です。作者は imie さんです。",
    tags: ["グランプリ", "こたえて", "imie"],
    caption: "湖面に最初のしるしが灯り、受賞曲の響きが広がります。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "kotaete-live-stage",
    songId: "kotaete",
    progress: 0.31,
    x: 0.55,
    y: 0.27,
    symbol: "♫",
    title: "ライブで演奏される歌",
    body: "グランプリ作品は、初音ミク「マジカルミライ 2026」のライブで演奏されます。",
    tags: ["ライブ", "ステージ", "受賞曲"],
    caption: "画面の湖面は、会場のステージへ続く入口になります。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "kotaete-sonare-theme",
    songId: "kotaete",
    progress: 0.56,
    x: 0.28,
    y: 0.38,
    symbol: "♩",
    title: "湖のソナーレ",
    body: "ソナーレはイタリア語で「奏でる」という意味。浜松での初開催にあわせて、湖と音楽をモチーフにしたテーマです。",
    tags: ["湖", "奏でる", "テーマ"],
    caption: "この湖は、音楽が水面に映る場所として描かれています。",
    sourceLabel: "piapro blog",
    sourceUrl: "https://blog.piapro.net/2026/03/b2603051.html",
  },
  {
    id: "kotaete-imie-comment",
    songId: "kotaete",
    progress: 0.82,
    x: 0.66,
    y: 0.23,
    symbol: "♬",
    title: "imieさんの受賞コメント",
    body: "imie さんは結果発表で、ミクさんがこの曲をステージで歌って踊る姿を楽しみにしている、とコメントしています。",
    tags: ["imie", "コメント", "ステージ"],
    caption: "作者の言葉も、ライブへ向かう小さな波になります。",
    sourceLabel: "piapro",
    sourceUrl: "https://piapro.jp/pages/official_collabo/magical2026_musiccontest/result",
  },
  {
    id: "curtain-hamamatsu-first",
    songId: "after-the-curtain",
    progress: 0.10,
    x: 0.24,
    y: 0.22,
    symbol: "♭",
    title: "初開催の浜松",
    body: "マジカルミライ 2026 は、TOKYO・OSAKAに加えて初めて HAMAMATSU でも開催されます。",
    tags: ["浜松", "初開催", "2026"],
    caption: "新しい会場の幕開けが、湖の向こうに重なります。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-act-city",
    songId: "after-the-curtain",
    progress: 0.32,
    x: 0.60,
    y: 0.33,
    symbol: "♯",
    title: "アクトシティ浜松",
    body: "HAMAMATSU会場はアクトシティ浜松。大ホール、展示イベントホール、コングレスセンターでライブと企画展が開かれます。",
    tags: ["アクトシティ", "会場", "浜松"],
    caption: "湖畔の風景の先には、実際の会場があります。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-live-exhibition",
    songId: "after-the-curtain",
    progress: 0.57,
    x: 0.36,
    y: 0.43,
    symbol: "♮",
    title: "ライブと企画展",
    body: "マジカルミライは、初音ミクたちバーチャルシンガーの3DCGライブと、創作の楽しさを体感できる企画展を併催するイベントです。",
    tags: ["ライブ", "企画展", "創作"],
    caption: "歌を聴く時間と、創作に触れる時間が同じ場所でつながります。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "curtain-creative-place",
    songId: "after-the-curtain",
    progress: 0.82,
    x: 0.68,
    y: 0.18,
    symbol: "♪",
    title: "創作でつながる場所",
    body: "マジカルミライは、作品やクリエイター、同じキャラクターが好きな人たちが「創作」をきっかけにつながる場所を目指しています。",
    tags: ["創作", "クリエイター", "未来"],
    caption: "小さなしるしも、誰かの創作へ続く入口です。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-lake-light",
    songId: "shutter-chance",
    progress: 0.10,
    x: 0.18,
    y: 0.27,
    symbol: "♫",
    title: "光を写す湖",
    body: "2026年のメインビジュアルは、湖や自然からの光に輝く様子と、音楽が華やかに響く様子を表現しています。",
    tags: ["光", "湖", "メインビジュアル"],
    caption: "水面に触れた光が、歌の一瞬を残します。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-main-visual-artist",
    songId: "shutter-chance",
    progress: 0.33,
    x: 0.51,
    y: 0.40,
    symbol: "♩",
    title: "緜さんのメインビジュアル",
    body: "初音ミク「マジカルミライ 2026」のメインビジュアルは、イラストレーターの 緜 さんが担当しています。",
    tags: ["緜", "ビジュアル", "湖"],
    caption: "画面の色と光は、公式ビジュアルの湖の印象につながっています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "shutter-costume-motifs",
    songId: "shutter-chance",
    progress: 0.58,
    x: 0.30,
    y: 0.20,
    symbol: "♬",
    title: "ひまわりと蝶と音符",
    body: "2026年の衣装デザインには、ひまわり、蝶、音符のモチーフがアクセントとして配されています。",
    tags: ["衣装", "ひまわり", "音符"],
    caption: "小さなモチーフが、湖の上のしるしにも重なります。",
    sourceLabel: "piapro blog",
    sourceUrl: "https://blog.piapro.net/2026/03/b2603051.html",
  },
  {
    id: "shutter-theme-song",
    songId: "shutter-chance",
    progress: 0.82,
    x: 0.64,
    y: 0.35,
    symbol: "♭",
    title: "テーマソング「空に免じて」",
    body: "マジカルミライ 2026 のテーマソングは、傘村トータ feat. 初音ミク「空に免じて」。編曲は島田昌典が担当しています。",
    tags: ["テーマソング", "空に免じて", "初音ミク"],
    caption: "湖面に映る空も、2026年の音楽の一部です。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "last-band-six-singers",
    songId: "last-band",
    progress: 0.10,
    x: 0.22,
    y: 0.36,
    symbol: "♯",
    title: "六人のバーチャルシンガー",
    body: "マジカルミライ 2026 では、初音ミク、鏡音リン、鏡音レン、巡音ルカ、MEIKO、KAITO がイベントを盛り上げます。",
    tags: ["初音ミク", "6人", "バーチャルシンガー"],
    caption: "六つの声が、湖の上で音楽隊のように並びます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "last-band-city-of-music",
    songId: "last-band",
    progress: 0.32,
    x: 0.58,
    y: 0.23,
    symbol: "♮",
    title: "音楽のまち浜松",
    body: "浜松市は、ピアノをはじめとする楽器産業を背景に発展し、昭和56年から「音楽のまちづくり」を掲げてきました。",
    tags: ["浜松", "音楽", "楽器"],
    caption: "湖の向こうには、楽器の音で育った街があります。",
    sourceLabel: "浜松市",
    sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/bunka/intro/mc/index.html",
  },
  {
    id: "last-band-instrument-museum",
    songId: "last-band",
    progress: 0.57,
    x: 0.34,
    y: 0.18,
    symbol: "♪",
    title: "楽器博物館",
    body: "浜松市楽器博物館は、日本初の公立楽器博物館です。世界各地から集めた約1500点の資料を地域、種類、年代別に展示しています。",
    tags: ["楽器博物館", "1500点", "音楽文化"],
    caption: "世界の楽器の記憶が、浜松の音楽文化を支えています。",
    sourceLabel: "Hamamatsu Museum",
    sourceUrl: "https://www.gakkihaku.jp/en/",
  },
  {
    id: "last-band-music-capital",
    songId: "last-band",
    progress: 0.82,
    x: 0.66,
    y: 0.42,
    symbol: "♫",
    title: "楽器のまちから音楽の都へ",
    body: "浜松市は、楽器のまちから文化面での発展を目指し、国際レベルから市民レベルまで多くの音楽施策を続けてきました。",
    tags: ["音楽の都", "文化", "浜松"],
    caption: "楽器づくりの街から、音楽を楽しむ街へ響きが広がります。",
    sourceLabel: "浜松市",
    sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/bunka/intro/mc/index.html",
  },
  {
    id: "toritsukurogy-bentenjima-torii",
    songId: "toritsukurogy",
    progress: 0.10,
    x: 0.24,
    y: 0.20,
    symbol: "♩",
    title: "弁天島の鳥居",
    body: "弁天島海浜公園では、浜名湖に立つ赤い鳥居がシンボルタワーとして親しまれています。",
    tags: ["弁天島", "鳥居", "浜名湖"],
    caption: "画面の鳥居は、湖の場所性を示すしるしです。",
    sourceLabel: "浜松・浜名湖だいすきネット",
    sourceUrl: "https://hamamatsu-daisuki.net/course/190/",
  },
  {
    id: "toritsukurogy-lake-hamana",
    songId: "toritsukurogy",
    progress: 0.32,
    x: 0.56,
    y: 0.38,
    symbol: "♬",
    title: "浜名湖のほとり",
    body: "浜松市の公式観光サイトでは、浜松を大都市の喧騒から離れて落ち着ける、静かな湖畔のある街として紹介しています。",
    tags: ["浜名湖", "湖畔", "浜松"],
    caption: "この風景は、浜松の湖畔の穏やかさを借りています。",
    sourceLabel: "Visit Hamamatsu",
    sourceUrl: "https://www.hamamatsu-japan.com/en/",
  },
  {
    id: "toritsukurogy-red-on-water",
    songId: "toritsukurogy",
    progress: 0.57,
    x: 0.33,
    y: 0.31,
    symbol: "♭",
    title: "湖に立つ赤",
    body: "浜名湖に立つ赤い鳥居は、弁天島の風景を象徴する存在です。湖面、夕景、ライトアップとともに記憶される景色です。",
    tags: ["赤い鳥居", "夕景", "湖面"],
    caption: "赤い輪郭が、水面の色と時間の変化を受け止めます。",
    sourceLabel: "浜松・浜名湖だいすきネット",
    sourceUrl: "https://hamamatsu-daisuki.net/course/190/",
  },
  {
    id: "toritsukurogy-lake-creatures",
    songId: "toritsukurogy",
    progress: 0.82,
    x: 0.68,
    y: 0.26,
    symbol: "♯",
    title: "浜名湖の生きもの",
    body: "浜松市の観光サイトでは、浜名湖の生き物を紹介する学習施設「浜名湖体験学習施設ウォット」が紹介されています。",
    tags: ["浜名湖", "生きもの", "ウォット"],
    caption: "水面の下にも、浜名湖の記憶があります。",
    sourceLabel: "Visit Hamamatsu",
    sourceUrl: "https://www.hamamatsu-japan.com/en/",
  },
  {
    id: "takeover-three-venues",
    songId: "takeover",
    progress: 0.10,
    x: 0.20,
    y: 0.30,
    symbol: "♮",
    title: "三会場へ広がる響き",
    body: "マジカルミライ 2026 は、HAMAMATSU、OSAKA、TOKYO の3会場で開催されます。",
    tags: ["HAMAMATSU", "OSAKA", "TOKYO"],
    caption: "ひとつの波は、三つの会場へ広がっていきます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-hatsune-miku",
    songId: "takeover",
    progress: 0.32,
    x: 0.54,
    y: 0.21,
    symbol: "♪",
    title: "初音ミクとは？",
    body: "初音ミクは、歌詞とメロディーを入力すると歌わせることができる歌声合成ソフトウェアとして、2007年に企画・開発されました。",
    tags: ["初音ミク", "2007", "歌声合成"],
    caption: "入力された言葉とメロディーが、歌として水面に届きます。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-creative-culture",
    songId: "takeover",
    progress: 0.57,
    x: 0.36,
    y: 0.41,
    symbol: "♫",
    title: "58万人の創作文化",
    body: "マジカルミライは2013年から開催され、国内では累計58万人以上を動員しています。",
    tags: ["58万人", "創作文化", "マジカルミライ"],
    caption: "小さなしるしも、大きな創作文化の流れにつながっています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
  {
    id: "takeover-miku-expo",
    songId: "takeover",
    progress: 0.82,
    x: 0.66,
    y: 0.35,
    symbol: "♬",
    title: "MIKU EXPOの広がり",
    body: "初音ミクの世界ツアーシリーズ「MIKU EXPO」は、これまでに50都市で120公演を巡演しています。",
    tags: ["MIKU EXPO", "世界ツアー", "初音ミク"],
    caption: "浜松から広がる響きは、世界のステージにも続いています。",
    sourceLabel: "Magical Mirai 2026",
    sourceUrl: "https://magicalmirai.com/2026/",
  },
];
